import { Service, ServiceCategory } from "@/types";

export const serviceCategories: ServiceCategory[] = [
  {
    name: "Build",
    description: "Digital products and systems built around how your business actually operates.",
    isPrimary: true,
  },
  {
    name: "AI & Automation",
    description: "Practical AI tools that improve content, customer communication, and repetitive operations.",
    isPrimary: true,
  },
  {
    name: "Grow & Support",
    description: "Supporting services that improve your digital presence and keep important work moving.",
    isPrimary: false,
  },
];

export const services: Service[] = [
  // Category 1: Build
  {
    name: "Web Development",
    slug: "web-development",
    category: "Build",
    shortDescription: "Fast, responsive websites built to represent your business clearly and turn visits into enquiries, bookings, or orders.",
    featured: true,
    displayOrder: 1,
    iconName: "Globe",
    metaTitle: "Web Development Services | KoDriftDev",
    metaDescription: "Fast, responsive websites built for Pakistani SMBs and international businesses to convert visitors into customers.",
    pageIntro: "Your website is often the first operational touchpoint for prospective clients. We build clean, high-speed web platforms tailored to your business model.",
    outcomes: [
      "A professional online presence that works on every screen",
      "Clear paths for customers to contact, enquire, book, or buy",
      "A secure, maintainable foundation that can grow with your business",
    ],
    deliverables: [
      "Responsive custom web application or business site",
      "Mobile-optimized layouts with fast load times",
      "Conversion-focused user flows and enquiry pathways",
      "Clean content architecture ready for scaling",
    ],
    processNote: "We design and develop iteratively with direct reviews to match your commercial priorities.",
    ctaText: "Discuss Your Project",
  },
  {
    name: "App Development",
    slug: "app-development",
    category: "Build",
    shortDescription: "Practical mobile and web applications designed around real customer and business workflows.",
    featured: true,
    displayOrder: 2,
    iconName: "Smartphone",
    metaTitle: "App Development Services | KoDriftDev",
    metaDescription: "Practical mobile and web applications designed around real customer and business workflows.",
    pageIntro: "When off-the-shelf software doesn't fit your operational flow, custom applications bridge the gap between your staff and customers.",
    outcomes: [
      "Easy-to-use experiences for customers and internal teams",
      "Modern app interfaces built for performance",
      "A clear foundation for future features and scale",
    ],
    deliverables: [
      "Cross-platform or web application architecture",
      "Role-based user flows and secure access",
      "Intuitive navigation for internal teams and customers",
      "Maintainable codebase prepared for future features",
    ],
    processNote: "From workflow mapping to tested builds, we focus on real-world business usability.",
    ctaText: "Discuss Your Project",
  },
  {
    name: "Software Development",
    slug: "software-development",
    category: "Build",
    shortDescription: "Custom business software that replaces repetitive manual work with connected, reliable systems.",
    featured: true,
    displayOrder: 3,
    iconName: "Cpu",
    metaTitle: "Software Development Services | KoDriftDev",
    metaDescription: "Custom business software that replaces repetitive manual work with connected, reliable systems.",
    pageIntro: "Businesses outgrow spreadsheets and disconnected tools. We engineer focused internal software that streamlines core daily operations.",
    outcomes: [
      "Centralized workflows, data, and reporting",
      "Less time lost to spreadsheets, registers, and manual follow-ups",
      "Software shaped around your operations, not generic limitations",
    ],
    deliverables: [
      "Centralized operational dashboards",
      "Automated records, ledger, or order management modules",
      "Data consistency and error-reduction safeguards",
      "Staff onboarding documentation and handover guidance",
    ],
    processNote: "We collaborate closely to capture operational bottlenecks before coding starts.",
    ctaText: "Discuss Your Project",
  },

  // Category 2: AI & Automation
  {
    name: "AI Product Photography",
    slug: "ai-product-photography",
    category: "AI & Automation",
    shortDescription: "High-quality AI-generated product visuals that help e-commerce products look ready for catalogues, ads, and social media.",
    featured: true,
    displayOrder: 4,
    iconName: "Camera",
    metaTitle: "AI Product Photography | KoDriftDev",
    metaDescription: "High-quality AI-generated product visuals that help e-commerce products look ready for catalogues, ads, and social media.",
    pageIntro: "Commercial studio shoots are expensive and time-consuming. We produce high-fidelity product imagery positioned in photorealistic lifestyle scenes.",
    outcomes: [
      "Premium product images without repeated studio shoots",
      "Multiple backgrounds, styles, campaigns, and formats",
      "Ready-to-use visuals for product pages, ads, and social content",
    ],
    deliverables: [
      "High-resolution e-commerce catalog renders",
      "Lifestyle and contextual background variations",
      "Social media and advertising ad-ready formats",
      "Rapid turnaround for seasonal campaign variants",
    ],
    processNote: "Send your product photos or CAD renders, and we generate consistent commercial-grade scenes.",
    ctaText: "Discuss Your Project",
  },
  {
    name: "AI Automation",
    slug: "ai-automation",
    category: "AI & Automation",
    shortDescription: "Chatbots and automated workflows that handle repetitive tasks, organize leads, and keep teams moving.",
    featured: true,
    displayOrder: 5,
    iconName: "Bot",
    metaTitle: "AI Automation & Chatbots | KoDriftDev",
    metaDescription: "Chatbots and automated workflows that handle repetitive tasks, organize leads, and keep teams moving.",
    pageIntro: "Cut out manual busywork. We integrate intelligent bots and automated webhook pipelines to handle client enquiries and internal notifications.",
    outcomes: [
      "Faster replies to customer questions",
      "Less manual copying between tools and spreadsheets",
      "Workflows built with platforms such as n8n and Make",
    ],
    deliverables: [
      "Automated lead capture and WhatsApp / email routing",
      "Custom conversational chatbots for enquiry triaging",
      "n8n / Make integration workflows",
      "Notification bots for team operational alerts",
    ],
    processNote: "Workflows are tested thoroughly against edge cases to prevent false responses.",
    ctaText: "Discuss Your Project",
  },

  // Category 3: Grow & Support
  {
    name: "Website Redesign",
    slug: "website-redesign",
    category: "Grow & Support",
    shortDescription: "A focused redesign for outdated, slow, confusing, or mobile-unfriendly websites.",
    featured: false,
    displayOrder: 6,
    iconName: "RefreshCw",
    metaTitle: "Website Redesign Services | KoDriftDev",
    metaDescription: "A focused redesign for outdated, slow, confusing, or mobile-unfriendly websites.",
    pageIntro: "If your current website no longer reflects the quality of your business or loses mobile visitors, we rebuild it with modern clarity.",
    outcomes: [
      "A clearer, more credible online presence",
      "Improved mobile experience and usability",
      "A design that supports enquiries and conversions",
    ],
    deliverables: [
      "Audit of current site weaknesses and drop-off points",
      "Modernized visual design aligned with your brand",
      "Responsive, clean code rebuilding the frontend",
      "Preservation of existing search ranking URLs where possible",
    ],
    processNote: "We focus on real commercial improvements rather than superficial decoration.",
    ctaText: "Discuss Your Project",
  },
  {
    name: "SEO",
    slug: "seo",
    category: "Grow & Support",
    shortDescription: "Practical search optimization that helps the right people find your business online.",
    featured: false,
    displayOrder: 7,
    iconName: "Search",
    metaTitle: "Search Engine Optimization (SEO) | KoDriftDev",
    metaDescription: "Practical search optimization that helps the right people find your business online.",
    pageIntro: "Search visibility shouldn't be a mystery. We establish structured technical foundations and keyword alignment for real local and global search intent.",
    outcomes: [
      "Improved on-page structure and technical foundations",
      "Content aligned with what customers actually search",
      "Clear reporting and realistic growth priorities",
    ],
    deliverables: [
      "Technical site audit and metadata configuration",
      "Keyword intent mapping for services and products",
      "Schema markup and indexing optimization",
      "Actionable recommendations for ongoing search relevance",
    ],
    processNote: "We prioritize realistic, measurable progress without exaggerated promises.",
    ctaText: "Discuss Your Project",
  },
  {
    name: "Graphic Design",
    slug: "graphic-design",
    category: "Grow & Support",
    shortDescription: "Professional visual assets for brands, campaigns, social media, presentations, and digital products.",
    featured: false,
    displayOrder: 8,
    iconName: "Palette",
    metaTitle: "Graphic Design Services | KoDriftDev",
    metaDescription: "Professional visual assets for brands, campaigns, social media, presentations, and digital products.",
    pageIntro: "Consistent visual presentation builds customer trust. We create clean, brand-aligned graphics for all your digital touchpoints.",
    outcomes: [
      "Consistent visuals across customer touchpoints",
      "Assets designed for the platform where they will be used",
      "Design support that fits your web, marketing, and product work",
    ],
    deliverables: [
      "Social media templates and campaign banners",
      "Brand identity assets and typography guidance",
      "Pitch deck and business presentation visuals",
      "Web and application UI graphics",
    ],
    processNote: "Assets are organized and provided in optimized digital production formats.",
    ctaText: "Discuss Your Project",
  },
  {
    name: "Digital Marketing",
    slug: "digital-marketing",
    category: "Grow & Support",
    shortDescription: "Campaign and content support that helps businesses communicate consistently and reach the right audience.",
    featured: false,
    displayOrder: 9,
    iconName: "Megaphone",
    metaTitle: "Digital Marketing Support | KoDriftDev",
    metaDescription: "Campaign and content support that helps businesses communicate consistently and reach the right audience.",
    pageIntro: "Having a great product is only half the battle. We help businesses communicate clear offers and reach relevant customers.",
    outcomes: [
      "Clear campaign messages and content direction",
      "Marketing assets built around practical business goals",
      "Support for social media, launches, and promotions",
    ],
    deliverables: [
      "Targeted campaign structure and messaging guidelines",
      "Content calendar recommendations",
      "Promotional creative direction and asset coordination",
      "Performance review and iteration notes",
    ],
    processNote: "Focused on straightforward, customer-centric messaging rather than vanity metrics.",
    ctaText: "Discuss Your Project",
  },
  {
    name: "Data Entry",
    slug: "data-entry",
    category: "Grow & Support",
    shortDescription: "Accurate, organized data support for businesses that need clean records, structured files, and reliable administrative help.",
    featured: false,
    displayOrder: 10,
    iconName: "FileSpreadsheet",
    metaTitle: "Data Entry & Organization | KoDriftDev",
    metaDescription: "Accurate, organized data support for businesses that need clean records, structured files, and reliable administrative help.",
    pageIntro: "Messy spreadsheets slow operations down. We assist businesses with clean record structuring, migration, and administrative data hygiene.",
    outcomes: [
      "More organized information and records",
      "Reduced backlog of repetitive administrative tasks",
      "Flexible support matched to your business process",
    ],
    deliverables: [
      "E-commerce product catalog upload and formatting",
      "Spreadsheet cleaning, deduplication, and structuring",
      "Data migration between legacy software and new systems",
      "Quality assurance and verification checks",
    ],
    processNote: "Handled with care, structured workflows, and data accuracy verification.",
    ctaText: "Discuss Your Project",
  },
];
